apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
          - env: staging
          - env: qa
  template:
    metadata:
      name: '{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/altus34/gitops-cert-level-2-examples
        targetRevision: HEAD
        path: './environment-promotion/envs/{{env}}'

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

